"""Build notebooks/walkthrough.ipynb programmatically with nbformat.

Run:  .venv\\Scripts\\python.exe notebooks\\_build_walkthrough.py
Then execute:  .venv\\Scripts\\python.exe -m nbconvert --to notebook --execute \\
                   --inplace notebooks\\walkthrough.ipynb

The notebook is a short narrative that EXECUTES clean: draw a population ->
observe it (funnel) -> fit one galaxy (aware vs naive corner overlay) -> show the
money plot + coverage curve from disk -> the hierarchical result.  Live compute
is kept light (one forward draw, one fast aware+naive fit with few live points);
the heavy figures are loaded from disk (regenerated by the scripts).
"""

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)


def md(text):
    return new_markdown_cell(text)


def code(text):
    return new_code_cell(text)


cells = []

cells.append(md(
    "# xrb-xlf-forwardmodel: end-to-end walkthrough\n"
    "\n"
    "A short narrative through the whole pipeline: **draw** a synthetic XRB "
    "population, **observe** it through a realistic selection funnel, **fit** one "
    "galaxy two ways (selection-aware vs naive), then look at the repo's main "
    "figures (the recovery **money plot**, the posterior **coverage curve**, and "
    "the **hierarchical stack**), all assembled from the full runs.\n"
    "\n"
    "Everything is reproducible from `configs/*.yaml` + the global seed. This "
    "notebook does light live compute (one draw, one fast fit) and loads the "
    "expensive figures from disk."
))

cells.append(code(
    "import os, sys\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import yaml\n"
    "\n"
    "# make src/ importable when running from notebooks/\n"
    "_REPO = os.path.dirname(os.getcwd()) if os.path.basename(os.getcwd()) == 'notebooks' else os.getcwd()\n"
    "sys.path.insert(0, os.path.join(_REPO, 'src'))\n"
    "\n"
    "from xlf_model.xlf import HMXBXLF, hmxb_from_config\n"
    "from xlf_model.forward import detector_from_config, run_forward, format_funnel\n"
    "from xlf_model.inference import make_hmxb_problem, fit_xlf\n"
    "\n"
    "with open(os.path.join(_REPO, 'configs', 'xlf_defaults.yaml')) as fh:\n"
    "    cfg = yaml.safe_load(fh)\n"
    "print('loaded config; global seed =', cfg['seed'])"
))

cells.append(md(
    "## 1. Draw a population\n"
    "\n"
    "Draw the HMXB population of a star-forming galaxy from the Mineo+12 XLF "
    "(ξ = 1.49, γ = 1.60). The number of sources is Poisson around the XLF "
    "integral above `L_min`; luminosities come from the analytic inverse CDF."
))

cells.append(code(
    "SFR = 30.0          # Msun/yr -- a vigorously star-forming galaxy\n"
    "distance_Mpc = 5.0  # nearby\n"
    "rng = np.random.default_rng(cfg['seed'])\n"
    "\n"
    "xlf = hmxb_from_config(cfg, SFR=SFR)\n"
    "print(f'HMXB XLF: xi={xlf.xi}, gamma={xlf.gamma}, band {xlf.band}')\n"
    "print(f'expected N(>L_min) = {xlf.expected_number():.1f} sources')"
))

cells.append(md(
    "## 2. Observe it: the selection funnel\n"
    "\n"
    "Push the intrinsic population through the deep `chandra_like` detector: "
    "luminosity → flux (distance + absorption), a **smooth completeness ramp** "
    "(no hard cut), and Poisson count noise (which produces Eddington bias). "
    "The funnel reports drawn → above-limit → detected."
))

cells.append(code(
    "detector = detector_from_config(cfg, name='chandra_like')\n"
    "res = run_forward(xlf, distance_Mpc, detector, rng,\n"
    "                  absorption_flux_factor=1.0, component='HMXB')\n"
    "print(format_funnel(res.funnel, title='HMXB funnel (this galaxy)'))\n"
    "\n"
    "L_obs = res.table['L_obs']\n"
    "L_obs = L_obs[L_obs > 0]\n"
    "print(f'\\nN detected = {L_obs.size}')"
))

cells.append(md(
    "## 3. Fit one galaxy two ways\n"
    "\n"
    "Fit the detected luminosities with the **selection-aware** likelihood (the "
    "completeness ramp) and the **naive** one (a hard flux cut, no ramp, no "
    "Eddington awareness). Same data, the only difference is `P_det`. We use a "
    "small live-point count here so the notebook runs fast; the full runs use 400."
))

cells.append(code(
    "from xlf_model.forward import luminosity_to_flux\n"
    "\n"
    "truth = {'log10_xi_eff': float(np.log10(xlf.xi * SFR)), 'gamma': float(xlf.gamma)}\n"
    "\n"
    "# selection-aware sees all detected sources\n"
    "like_aware = make_hmxb_problem(L_obs, cfg, distance_Mpc=distance_Mpc,\n"
    "                               detector=detector, selection_aware=True)\n"
    "# naive sees only sources above its own hard cut\n"
    "flux = luminosity_to_flux(L_obs, distance_Mpc)\n"
    "L_naive = L_obs[flux >= detector.flux_limit_50]\n"
    "like_naive = make_hmxb_problem(L_naive, cfg, distance_Mpc=distance_Mpc,\n"
    "                               detector=detector, selection_aware=False)\n"
    "\n"
    "fast = {'inference': {'sampler': {'n_live': 120}}}\n"
    "fr_aware = fit_xlf(like_aware, fast, sampler='ultranest', seed=1)\n"
    "fr_naive = fit_xlf(like_naive, fast, sampler='ultranest', seed=2)\n"
    "\n"
    "for name, fr in [('selection-aware', fr_aware), ('naive', fr_naive)]:\n"
    "    s = fr.summary()['gamma']\n"
    "    print(f'{name:>16}:  gamma = {s[\"median\"]:.3f} '\n"
    "          f'(-{s[\"minus\"]:.3f}/+{s[\"plus\"]:.3f})   truth = {truth[\"gamma\"]}')"
))

cells.append(md(
    "The naive fit flattens the slope: it discards the information that faint "
    "sources are present but under-counted. Overlay the two posteriors with the "
    "truth marked:"
))

cells.append(code(
    "import corner\n"
    "labels = [r'$\\log_{10}\\,\\xi_{\\rm eff}$', r'$\\gamma$']\n"
    "truths = [truth['log10_xi_eff'], truth['gamma']]\n"
    "both = np.vstack([fr_aware.samples, fr_naive.samples])\n"
    "rng_box = [(both[:, i].min(), both[:, i].max()) for i in range(both.shape[1])]\n"
    "pad = [0.1 * (hi - lo) for lo, hi in rng_box]\n"
    "rng_box = [(lo - p, hi + p) for (lo, hi), p in zip(rng_box, pad)]\n"
    "\n"
    "fig = corner.corner(fr_aware.samples, labels=labels, truths=truths,\n"
    "                    range=rng_box, color='C0', truth_color='k',\n"
    "                    plot_datapoints=False, hist_kwargs={'density': True},\n"
    "                    levels=(0.68, 0.95))\n"
    "corner.corner(fr_naive.samples, fig=fig, range=rng_box, color='C3',\n"
    "              plot_datapoints=False, hist_kwargs={'density': True},\n"
    "              levels=(0.68, 0.95))\n"
    "from matplotlib.lines import Line2D\n"
    "fig.legend(handles=[Line2D([0],[0],color='C0',lw=2,label='selection-aware'),\n"
    "                    Line2D([0],[0],color='C3',lw=2,label='naive (hard cut)'),\n"
    "                    Line2D([0],[0],color='k',lw=1.5,label='truth')],\n"
    "           loc='upper right', fontsize=10, bbox_to_anchor=(0.98, 0.92))\n"
    "plt.show()"
))

cells.append(md(
    "## 4. The money plot: bias & coverage vs N_det\n"
    "\n"
    "The single fit above is one realization; the systematic behaviour shows up "
    "over a grid of detected counts and many realizations. This figure "
    "comes from the full recovery suite (1480 fits, `scripts/run_recovery_suite.py` "
    "→ `analyze_recovery.py`). The naive fit is biased and its coverage collapses "
    "at high N; the selection-aware fit stays unbiased with near-nominal coverage."
))

cells.append(code(
    "from matplotlib import image as mpimg\n"
    "def show(path, figsize=(13, 6)):\n"
    "    full = os.path.join(_REPO, path)\n"
    "    if not os.path.exists(full):\n"
    "        print('(figure not found -- run the relevant script:', path, ')')\n"
    "        return\n"
    "    img = mpimg.imread(full)\n"
    "    plt.figure(figsize=figsize)\n"
    "    plt.imshow(img); plt.axis('off'); plt.show()\n"
    "\n"
    "show('outputs/recovery/money_plot.png')"
))

cells.append(md(
    "## 5. Posterior coverage curve\n"
    "\n"
    "Does the q% credible interval of the **correct** likelihood contain the truth "
    "q% of the time? Across 250 selection-aware fits at N_det ≈ 50 the curve is "
    "near-diagonal (max deviation 0.056), with a documented ~2% under-coverage "
    "from residual Eddington bias. This is the same coverage methodology the "
    "sibling `sbi-xray-calibration` repo uses on neural posteriors."
))

cells.append(code("show('outputs/recovery/coverage_curve.png')"))

cells.append(md(
    "## 6. Hierarchical stack: pooling faint galaxies\n"
    "\n"
    "Thirty galaxies sharing one global XLF, mostly in the few-detections regime, "
    "fit jointly. The joint fit is ≈ 2.4× tighter on γ than the single best "
    "galaxy, so the pooled few-detection galaxies constrain γ as well as the one "
    "richest galaxy."
))

cells.append(code("show('outputs/diagnostics/hierarchical_stack.png')"))

cells.append(md(
    "## Summary\n"
    "\n"
    "Ignoring the selection function biases the recovered HMXB slope by "
    "Δγ ≈ −0.05 (and worse for steeper XLFs), and its credible interval stops "
    "containing the truth: naive 68% coverage collapses to 0.10 at the bright "
    "end. The selection-aware unbinned Poisson-process likelihood is unbiased to "
    "|Δγ| ≤ 0.02 with coverage within a few percent of nominal across the whole "
    "5–500 detected-source range. The only residual is a ~2% under-coverage from "
    "Eddington bias, which is documented in RESULTS.md.\n"
    "\n"
    "See `RESULTS.md` for every number and `README.md` for the prior-work framing."
))

nb = new_notebook(cells=cells)
nb.metadata["kernelspec"] = {
    "display_name": "Python 3", "language": "python", "name": "python3",
}
nb.metadata["language_info"] = {"name": "python"}

out = os.path.join(_HERE, "walkthrough.ipynb")
with open(out, "w", encoding="utf-8") as fh:
    nbf.write(nb, fh)
print("wrote", out, "with", len(cells), "cells")
