r"""Regenerate every README figure from config + seed.

This script regenerates the five synthetic README figures from the result tables
(the sixth committed figure, real_galaxy_fit.png, is produced by run_real_demo.py),
each from its config and the global seed:

  figure                              produced from              config
  ----------------------------------  -------------------------  --------------------------
  outputs/recovery/money_plot.png     analyze_recovery.main()    configs/recovery_suite.yaml
  outputs/recovery/coverage_curve.png analyze_coverage.main()    configs/coverage.yaml
  outputs/diagnostics/lxsfr_*.png     run_lxsfr_demo.main()      configs/lxsfr_demo.yaml
  outputs/diagnostics/hierarchical_*  run_hierarchical.main()    configs/hierarchical.yaml
  outputs/diagnostics/demo_xlf_draw   run_forward_demo.main()    configs/xlf_defaults.yaml

The money plot and the coverage curve are ANALYSIS figures: they read the
results tables (results.jsonl / coverage_results.jsonl) produced by the
(expensive, parallel) fitting runs and re-draw the plot.  Those raw result
tables are NOT committed (they are gitignored); only the final PNGs are tracked.
Regenerating these two figures from scratch therefore means re-running the
recovery/coverage suites first (run_recovery_suite.py / run_coverage.py) to
rebuild the tables, then drawing the plot.  If a table is missing, this script
tells you which run to do first.  The three diagnostic figures (L_X-SFR,
hierarchical, forward demo) are self-contained Monte-Carlo / single-fit scripts
and regenerate fully from config+seed in seconds-to-a-minute each.

Usage
-----
    # regenerate every README figure:
    .venv\Scripts\python.exe scripts\make_plots.py --config all

    # regenerate one figure (give its config or its short name):
    .venv\Scripts\python.exe scripts\make_plots.py --config configs\coverage.yaml
    .venv\Scripts\python.exe scripts\make_plots.py --config money
"""

from __future__ import annotations

import argparse
import os
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "scripts"))
sys.path.insert(0, os.path.join(_REPO, "src"))

# Each figure is regenerated by calling the owning script's main() with the right
# --config.  Importing them as modules keeps one source of truth for each plot.
import analyze_coverage  # noqa: E402
import analyze_recovery  # noqa: E402
import run_forward_demo  # noqa: E402
import run_hierarchical  # noqa: E402
import run_lxsfr_demo  # noqa: E402


def _cfg(name):
    return os.path.join(_REPO, "configs", name)


# name -> (label, callable(main), [argv], results-table-needed-or-None)
FIGURES = {
    "money": (
        "money_plot.png (recovery suite)",
        analyze_recovery.main,
        ["--config", _cfg("recovery_suite.yaml")],
        os.path.join(_REPO, "outputs", "recovery", "results.jsonl"),
    ),
    "coverage": (
        "coverage_curve.png (posterior coverage validation)",
        analyze_coverage.main,
        ["--config", _cfg("coverage.yaml")],
        os.path.join(_REPO, "outputs", "recovery", "coverage_results.jsonl"),
    ),
    "lxsfr": (
        "lxsfr_nonlinearity.png (L_X-SFR nonlinearity)",
        run_lxsfr_demo.main,
        ["--config", _cfg("lxsfr_demo.yaml")],
        None,
    ),
    "hierarchical": (
        "hierarchical_stack.png (survey stack)",
        run_hierarchical.main,
        ["--config", _cfg("hierarchical.yaml")],
        None,
    ),
    "forward": (
        "demo_xlf_draw.png (forward-model funnel demo)",
        run_forward_demo.main,
        ["--config", _cfg("xlf_defaults.yaml")],
        None,
    ),
}

# map a --config value (a path or a short alias) to a figure key
ALIASES = {
    "all": None,
    "money": "money", "recovery_suite.yaml": "money", "recovery": "money",
    "coverage": "coverage", "coverage.yaml": "coverage",
    "lxsfr": "lxsfr", "lxsfr_demo.yaml": "lxsfr",
    "hierarchical": "hierarchical", "hierarchical.yaml": "hierarchical",
    "forward": "forward", "xlf_defaults.yaml": "forward", "demo": "forward",
}


def resolve(config_arg):
    """Map a --config value to one figure key, or None for 'all'."""
    base = os.path.basename(str(config_arg)).strip()
    low = base.lower()
    if low in ALIASES:
        return ALIASES[low]
    # also accept the figure key directly
    if low in FIGURES:
        return low
    raise SystemExit(
        f"unrecognised --config {config_arg!r}. Use 'all' or one of: "
        f"{', '.join(sorted(FIGURES))} (or a configs/*.yaml path)."
    )


def make_one(key):
    label, fn, argv, needs = FIGURES[key]
    print("=" * 72)
    print(f"[make_plots] regenerating {label}")
    print("=" * 72)
    if needs is not None and not os.path.exists(needs):
        run = ("run_recovery_suite.py" if key == "money"
               else "run_coverage.py")
        print(f"  SKIP: results table not found: {needs}")
        print(f"        run  .venv\\Scripts\\python.exe scripts\\{run}  first "
              f"(it produces the table this figure reads).")
        return False
    rc = fn(argv)
    return rc in (0, None)


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="all",
                   help="'all', a figure key (money/coverage/lxsfr/"
                        "hierarchical/forward), or a configs/*.yaml path")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    key = resolve(args.config)
    keys = list(FIGURES) if key is None else [key]
    ok = {}
    for k in keys:
        ok[k] = make_one(k)
        print()
    print("=" * 72)
    print("[make_plots] summary")
    for k in keys:
        status = "OK" if ok[k] else "SKIPPED (see note above)"
        print(f"  {FIGURES[k][0]:<55} {status}")
    print("=" * 72)
    return 0 if all(ok.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
